In [ ]:
def add_number(a, b):
  return a+b
add_number(4, 6)

10

In [ ]:
def sub_number(a, b):
  return a-b
sub_number(4, 6)

-2

In [ ]:
price= 4000
print("Price after 5% discount is:", price-5/100*price)
print("Price after 10% discount is:", price-10/100*price)
print("Price after 15% discount is:", price-15/100*price)
print("Price after 20% discount is:", price-20/100*price)

Price after 5% discount is: 3800.0
Price after 10% discount is: 3600.0
Price after 15% discount is: 3400.0
Price after 20% discount is: 3200.0


In [ ]:
list1=[]
for i in range(1,11):
  if i%2==0:
    list1.append(i**2)
list1

[4, 16, 36, 64, 100]

In [ ]:
table=[["Name", "Age", "City"],
       ["John", 26, "New York"],
       ["Alice", 23, "Japan"],
       ["Jimin", 28, "South Korea"]]
print(table)

[['Name', 'Age', 'City'], ['John', 26, 'New York'], ['Alice', 23, 'Japan'], ['Jimin', 28, 'South Korea']]


In [ ]:
def my_square(x):
  return x**2
number= [1,3,5,7,9]
squared= (map(my_square, number))
tuple(squared)

(1, 9, 25, 49, 81)

In [ ]:
def power(a, b):
    if b == 0:
        return 1
    return a * power(a, b - 1)

print(power(2, 3))


8


In [ ]:
def print_squares():
    squares = [i**2 for i in range(1, 31)]
    print("Squares of numbers from 1 to 30:")
    print(squares)
print_squares()

Squares of numbers from 1 to 30:
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900]


In [ ]:
keys = ['Class-V', 'Class-VI', 'Class-VII', 'Class-VIII']
values = [1, 2, 2, 3]
class_dict = {}

# Populate the dictionary
for key, value in zip(keys, values):
    if key not in class_dict:
        class_dict[key] = set()
    class_dict[key].add(value)

# Print the dictionary
print(class_dict)

{'Class-V': {1}, 'Class-VI': {2}, 'Class-VII': {2}, 'Class-VIII': {3}}


In [ ]:
#Trigonometric functions
import numpy as np
np.exp(2)

np.float64(7.38905609893065)

In [ ]:
arr5= np.array([2,4,6])
np.exp(arr5)

array([  7.3890561 ,  54.59815003, 403.42879349])

In [ ]:
np.log(2)   #base e

np.float64(0.6931471805599453)

In [ ]:
np.log10(2)   #base 10

np.float64(0.3010299956639812)

In [ ]:
arr7= np.arange(1,6)
arr8= np.arange(3,8)
print(arr7)
print(arr8)

[1 2 3 4 5]
[3 4 5 6 7]


In [ ]:
print('Addition: ',arr7+arr8)
print('Subtarction: ',arr8-arr7)
print('Multiplisation: ',arr7*arr8)
print('Division: ',arr7/arr8)
print('Inverse: ',1/arr8)
print('Powers: ',arr7 ** arr8)

Addition:  [ 4  6  8 10 12]
Subtarction:  [2 2 2 2 2]
Multiplisation:  [ 3  8 15 24 35]
Division:  [0.33333333 0.5        0.6        0.66666667 0.71428571]
Inverse:  [0.33333333 0.25       0.2        0.16666667 0.14285714]
Powers:  [    1    16   243  4096 78125]


In [ ]:
#LINEAR ALGEBRA
matrix3= np.arange(1,10).reshape(3,3)
matrix4= np.eye(3,3)  #for identity matrix
print(matrix3)
print('\n')
print(matrix4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(matrix3+matrix4)
print('\n')
print(matrix3-matrix4)
print('\n')
print(matrix3*matrix4)
print('\n')
print(matrix3/matrix4)

[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


[[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]


[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]


[[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


<ipython-input-12-da9d6d8f88a0>:7: RuntimeWarning: divide by zero encountered in divide
  print(matrix3/matrix4)


In [ ]:
dot_product = np.dot(matrix3, matrix4)
print(dot_product)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
#Solve these equations for X,Y,Z
# X+ 2Y+ 3Z= 10
# 2X+ 3Y+ Z= 15
# X+ Y+ 2Z= 20

In [ ]:
# Coefficients of the equations
A = np.array([[1, 2, 3],[2, 3, 1],[1, 1, 2]])

# Constants on the right-hand side
B = np.array([10, 15, 20])

# Solve the system of equations
X,Y,Z = np.linalg.solve(A, B)
print("X =", X)
print("Y =", Y)
print("Z =", Z)

X = 26.25
Y = -13.75
Z = 3.75


In [ ]:
print(matrix3)
np.transpose(matrix3)   #or matrix3.T

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.max(matrix3)

np.int64(9)

In [ ]:
np.min(matrix3)

np.int64(1)

In [ ]:
np.sum(matrix3)

np.int64(45)

In [ ]:
rand_mat1=np.random.randn(1000)
print(rand_mat1)

[-5.64463161e-01  1.39530156e+00  1.05690600e+00 -3.02180816e-01
  1.81489340e-01 -6.02556349e-01 -7.73031522e-01  6.11427444e-01
  2.21405833e-01 -6.73936425e-01 -1.77798436e+00  1.75267942e-02
  1.32239546e+00  8.66744301e-01  5.14026372e-01 -2.08872904e-01
 -1.35823582e-01 -1.24059641e+00 -2.95081069e-01 -4.52437673e-01
  2.59170248e-01  1.04456899e-01  8.29410486e-01 -1.59733180e-01
  5.85577519e-01  2.05664532e+00  1.83777098e-02 -3.63030564e+00
 -8.75761917e-03 -1.31975789e+00  7.19758444e-01  5.77408647e-01
 -4.76161144e-01  2.65334895e+00 -2.51324371e-02  1.24110042e+00
  1.02308922e+00  4.92416707e-02 -5.85329482e-01  6.56614445e-01
 -2.50974650e+00  4.33237987e-01 -3.69692814e-01  1.94533842e+00
  8.46529022e-01  7.00416620e-01  2.83969485e-01  1.36255935e+00
 -5.91285896e-01 -2.33228605e-01  1.87649651e+00  1.77328971e-01
  6.90754748e-01 -1.03451934e+00  1.42532991e+00  4.30891037e-01
 -2.27259455e-01 -7.05675008e-01  7.57158063e-01 -3.20746830e-01
  4.42917314e-01  1.46269

In [ ]:
print(np.mean(rand_mat1))
print(np.std(rand_mat1))

0.01874595462111931
1.0165181394091984


In [ ]:
#Pandas dataframe using a dict
import pandas as pd
student= ['Mary','Sam','Peter','Susan','Lily','Toby']
grades= ['B','A+','A','B+','C']
df2= pd.DataFrame(('Student':student,'Grade':grades))
df2

Student Grades
0    Mary      B
1     Sam     A+
2   Peter      A
3   Susan     B+
4    Lily      C
5    Toby      D